# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
#  ----------------------------- cryptogen 模块 ---------------------------------------
# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
OrdererOrgs:             ###定义orderer节点 排序节点组织的名字
  # ---------------------------------------------------------------------------
  # Orderer
  # ---------------------------------------------------------------------------
  - Name: Orderer                           ### 排序节点组织的名字
    Domain: c4BlockChain.com                ###orderer节点的根域名 测试环境中可以随便写，但是真实网络这个域名要写已注册的域名
    # ---------------------------------------------------------------------------
    # "Specs" - See PeerOrgs below for complete description
    # orderer组织中的orderer节点的名字。solo模式中只有一个，在之后的kafka模式下可以挂载多个orderer节点
    # ---------------------------------------------------------------------------
    Specs:    
      - Hostname: orderer                   ###orderer节点的主机名
# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  ##### 暂时在配置文件中定义了2个组织  一个组织代表一家医院 后期可以在fabric-ca-sdk中动态添加组织
  # ---------------------------------------------------------------------------
  # Org1   
  # ---------------------------------------------------------------------------
  - Name: youaiHospital          ### 当前组织的名字
    Domain: youai.c4BlockChain.com
    EnableNodeOUs: true          # 是否在该peer组织下的msp目录中生成一个config.yaml文件 该文件用于身份识别 
    Template:                     #使用模板生成peer节点证书
      Count: 2                    ####组织中节点的数目 生成2个访问域名
     
    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin  定义了一个用户 
    # ---------------------------------------------------------------------------
    Users:
      Count: 1           #生成1个普通用户,另外还会默认生成管理员Admin用户
   
 # ---------------------------------------------------------------------------
  # Org2  
  # ---------------------------------------------------------------------------
  - Name: renaiHospital
    Domain: renai.c4BlockChain.com
    EnableNodeOUs: true
    Template:
      Count: 2                    ####组织中节点的数目
     
    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin  定义了一个用户 
    # ---------------------------------------------------------------------------
    Users:
      Count: 1

